### PR TITLE
Swift 3 and other improvements

### PR DESCRIPTION
**Pull request by einsteinx2**
I updated the framework and demo app code to Swift 3, added support for centered cells, custom cells drawing functions, touch bar including matching the stock touch bar slider style, and Carthage package management. Also fixed the target membership of the framework files which was causing broken syntax highlighting and other issues in Xcode.

### CODE REVIEW

**Comment by mmontag** [comment]
Hey @raiseandfall, you should merge this 😀

**Comment by raiseandfall** [comment]
Hey guys, I don't work at the studio anymore and I'm too busy to do pull requests reviews these days, but I'm sure somebody in the dev team can do it.

**Comment by raiseandfall** [comment]
@mmontag @einsteinx2 Actually, since I'm not part of the team anymore I don't have writing access to merge PR... so you really need to get somebody there to do it.

**Comment by raiseandfall** [comment]
Anybody? @chrisjstott @noahphillips

**Pull request merged**
